FROM --platform=linux/amd64 debian:12

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y \
    libgl-dev \
    libssl-dev \
    build-essential \
    cmake \
    libudev-dev \
    pkg-config \
    zip \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace

CMD ["/bin/bash"]
